# Generated by Django 2.2.7 on 2019-11-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('carrer', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
                ('service_units', models.CharField(max_length=20)),
                ('marital', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('dependents', models.IntegerField()),
                ('is_SYN', models.BooleanField()),
                ('is_register_web_bank', models.BooleanField()),
                ('is_app_bank', models.BooleanField()),
                ('is_register_mobile_pay', models.BooleanField()),
            ],
        ),
    ]
