# Generated by Django 2.2.7 on 2019-11-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ptype', models.CharField(choices=[('保險', '保險'), ('股票', '股票'), ('基金', '基金'), ('債券', '債券'), ('房貸', '房貸'), ('信用卡', '信用卡'), ('期貨', '期貨')], default='股票', max_length=10)),
            ],
        ),
    ]
