# Generated by Django 2.2.7 on 2019-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('ktype', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
    ]
