# Generated by Django 2.2.7 on 2019-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0007_remove_customer_is_syn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='a1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='a2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='a3',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='a4',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='a5',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='a6',
            field=models.IntegerField(default=5),
        ),
    ]
