# Generated by Django 2.2.3 on 2019-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0010_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='risk',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_company',
            field=models.CharField(choices=[['華南永信', '華南永信']], default='華南永信', max_length=10),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_country',
            field=models.CharField(choices=[['國內', '國內'], ['國外', '國外']], default='國內', max_length=10),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_risk',
            field=models.CharField(choices=[['RR1', 'RR1'], ['RR2', 'RR2'], ['RR3', 'RR3'], ['RR4', 'RR4'], ['RR5', 'RR5']], default='RR1', max_length=10),
        ),
    ]
