# Generated by Django 2.2.3 on 2019-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0011_auto_20191214_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
