# Generated by Django 2.2.5 on 2019-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0012_delete_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=50)),
            ],
        ),
    ]
