# Generated by Django 2.2.3 on 2019-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0013_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
    ]
