# Generated by Django 2.2.3 on 2019-12-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0014_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cocsite.risk'),
            preserve_default=False,
        ),
    ]
