# Generated by Django 2.2.5 on 2020-04-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0023_auto_20200409_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.CharField(max_length=50)),
                ('ans2', models.CharField(max_length=50)),
                ('ans3', models.CharField(max_length=50)),
                ('ans4', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(max_length=50),
        ),
    ]
