# Generated by Django 2.2.5 on 2020-04-10 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0032_auto_20200409_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
        migrations.CreateModel(
            name='Answer_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_sc', models.CharField(blank=True, max_length=50)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Score')),
            ],
        ),
    ]
