# Generated by Django 2.2.7 on 2020-05-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0058_auto_20200411_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_Article_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
        migrations.CreateModel(
            name='Fund_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cocsite.Fund_Article_Type')),
            ],
        ),
    ]
