# Generated by Django 2.2.7 on 2020-05-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0060_auto_20200504_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_article',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
    ]
