# Generated by Django 2.2.3 on 2020-05-14 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0063_auto_20200510_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('increase', models.CharField(blank=True, max_length=20)),
                ('increase_pct', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='fund_article',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='fund_article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='fund_article',
            name='url',
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
        migrations.AlterField(
            model_name='fund_article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
