# Generated by Django 2.2.7 on 2020-05-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocsite', '0066_auto_20200514_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=20)),
                ('income', models.PositiveIntegerField(default=0)),
                ('career', models.CharField(max_length=20)),
                ('gender', models.PositiveIntegerField(default=0)),
                ('is_app_bank', models.PositiveIntegerField(default=0)),
                ('marital', models.CharField(max_length=20)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('residence', models.CharField(max_length=20)),
                ('is_register_web_bank', models.PositiveIntegerField(default=0)),
                ('is_register_mobile_pay', models.PositiveIntegerField(default=0)),
                ('credit_level', models.CharField(max_length=20)),
                ('period', models.PositiveIntegerField(default=0)),
                ('balance_loan', models.PositiveIntegerField(default=0)),
                ('usage', models.CharField(max_length=20)),
                ('property_house', models.CharField(max_length=20)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('situation', models.CharField(max_length=20)),
                ('insurance_category', models.CharField(max_length=20)),
                ('insurance_premiums', models.PositiveIntegerField(default=0)),
                ('is_active', models.PositiveIntegerField(default=0)),
                ('is_blacklist', models.PositiveIntegerField(default=0)),
                ('claim_amount', models.PositiveIntegerField(default=0)),
                ('claim_descript', models.CharField(max_length=20)),
                ('dividend_category', models.CharField(max_length=20)),
                ('fund_name', models.CharField(max_length=20)),
                ('price_currency', models.CharField(max_length=20)),
                ('net', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='fund',
            name='rk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocsite.Risk'),
        ),
    ]
